### ISSUE TITLE
Don't install development/test dependencies.

### ISSUE THREAD

**Issue by MrJoy** [docker-library/rails#17]
Shouldn't the bundle command be `bundle install --without development test`?  Or at least allow some variant tags that do this?

**Comment by JohnMorales** [comment]
A little late to the party, but please see my pull request #25, moving bundle install and other setup commands to an entrypoint script adds the flexibility needed to use these images as development containers. Since in development you don't need to customize building a new image, simply what the container runs it's a perfect use case of entrypoint.

This pattern could be expanded to support custom apt-get commands.

**Comment by tianon** [comment]
Given that the recommended usage for Rails itself is to add it to your project's `Gemfile` and use `bundle` to install it, [the `rails` official image](https://hub.docker.com/_/rails/) has been deprecated as of Jul 5 in favor of using [the `ruby` image](https://hub.docker.com/_/ruby/) directly (see https://github.com/docker-library/docs/pull/503 for more details).

Sorry for the inconvenience!  Since the image will not be receiving anything besides minor maintenance updates (version bumps for example), we're closing out old issues accordingly.  Thanks!
