### ISSUE TITLE
Use non-root user

### ISSUE THREAD

**Issue by louy2** [docker-library/rails#30]
As suggested in [best practices](https://docs.docker.com/reference/builder/#user).

It also makes bundler complain.

Copied from [#223 under docker-library/docs](https://github.com/docker-library/docs/issues/223)

**Comment by yosifkit** [comment]
While it is true that we encourage users to run their images as not root and most official images do so by default, but this and other language images are often used for development with bind mounted local code.  Handling permissions there would be untenable and would cause the same issue as https://github.com/boot2docker/boot2docker/issues/581 for every user rather than just boot2docker users.
