### ISSUE TITLE
Need libxml2-dev libxslt1-dev to build rails

### ISSUE THREAD

**Issue by dove-young** [docker-library/rails#31]
Not sure which image your **From ruby:2.2** stands for.  I suppose it would be the image build from here: https://github.com/docker-library/ruby/tree/master/2.2

Then I tried to build on top of which I've build with wheezy image, then I found the following patch was needed to finish building. 

```
  diff -ub rails/Dockerfile Dockerfile
--- rails/Dockerfile    2015-05-26 16:18:13.650495822 +0800
+++ Dockerfile  2015-05-26 16:26:18.415989564 +0800
@@ -1,11 +1,19 @@
 FROM ruby:2.2
 
 # see update.sh for why all "apt-get install"s have to stay as one long line
-RUN apt-get update && apt-get install -y nodejs --no-install-recommends && rm -rf /var/lib/apt/lists/*
-
+RUN curl -sL https://deb.nodesource.com/setup | bash - \
+        && apt-get update \
+        && apt-get install -y nodejs --no-install-recommends \
+        && rm -rf /var/lib/apt/lists/*
 # see http://guides.rubyonrails.org/command_line.html#rails-dbconsole
-RUN apt-get update && apt-get install -y mysql-client postgresql-client sqlite3 --no-install-recommends && rm -rf /var/lib/apt/lists/*
-
+RUN apt-get update \
+        && apt-get install -y mysql-client postgresql-client sqlite3 \
+        && libxml2-dev libxslt1-dev --no-install-recommends \
+        && rm -rf /var/lib/apt/lists/*
 ENV RAILS_VERSION 4.2.1
+RUN gem install nokogiri -- --use-system-libraries
 RUN gem install rails --version "$RAILS_VERSION"
```

**Comment by tianon** [comment]
Given that the recommended usage for Rails itself is to add it to your project's `Gemfile` and use `bundle` to install it, [the `rails` official image](https://hub.docker.com/_/rails/) has been deprecated as of Jul 5 in favor of using [the `ruby` image](https://hub.docker.com/_/ruby/) directly (see https://github.com/docker-library/docs/pull/503 for more details).

Sorry for the inconvenience!  Since the image will not be receiving anything besides minor maintenance updates (version bumps for example), we're closing out old issues accordingly.  Thanks!
