### ISSUE TITLE
Logs go to a file instead of STDOUT

### ISSUE THREAD

**Issue by md5** [docker-library/rails#33]
I hadn't played around much with the `rails` image before this week, but I noticed that the logs are be written to the default `logs/#{Rails.env}.log` file instead of `STDOUT`.

I think the fix will need to be made for each app that is based on this image (or pretty much any other Dockerized Rails app), so I don't think there's anything to be done in the image itself. I believe the only thing that should be done is to document the issue over at `docker-library/docs`, so let me know if I should have opened the issue there. At least having the issue in this repo will help people find it if they search for the problem.

The Rails docs show a quick & dirty approach to logging to `STDOUT`: http://guides.rubyonrails.org/debugging_rails_applications.html#the-logger

There are also things like Heroku's `rails_stdout_logging` gem: https://github.com/heroku/rails_stdout_logging

**Comment by blackxored** [comment]
I think you're right, however there might be something you can actually do in the image. 

```
for env in development test production; do
  ln -sfn /dev/stdout log/$env.log
done
```

assuming workdirs and whatnot. 
I think I got this trick from the nginx image or something, can't recall. 

Then you'd probably wanna check if you're not getting buffering issues, but I think rails does STDOUT.sync = true I believe, maybe I've mixed thoughts.

**Comment by tianon** [comment]
Given that the recommended usage for Rails itself is to add it to your project's `Gemfile` and use `bundle` to install it, [the `rails` official image](https://hub.docker.com/_/rails/) has been deprecated as of Jul 5 in favor of using [the `ruby` image](https://hub.docker.com/_/ruby/) directly (see https://github.com/docker-library/docs/pull/503 for more details).

Sorry for the inconvenience!  Since the image will not be receiving anything besides minor maintenance updates (version bumps for example), we're closing out old issues accordingly.  Thanks!
