### ISSUE TITLE
rails 4.2.5 change

### ISSUE THREAD

**Issue by elimin8r** [docker-library/rails#36]
Is there anything different in the image which was pushed 2 hours ago that could cause it to break things?

**Comment by yosifkit** [comment]
Looks like we finally finished pushing all the changes from https://github.com/docker-library/official-images/pull/1376 which brought in https://github.com/docker-library/ruby/pull/63 and the bump to `4.2.5.1` and an updated debian base from https://github.com/docker-library/official-images/pull/1370.  Could any of those be causing any issues for you?  What is the problem that is happening?

**Comment by elimin8r** [comment]
I am seeing an issue where inside and outside the container i can only lynx
to rails on 127.0.0.1:3000. Previous behavior allowed me to lynx either
localhost:3000 or 0.0.0.0:3000. My guess is it might be a change in the
debian base related to how lynx resolves localhost. Interestingly, telnet
resolves localhost correctly. Not sure if this will cause others any
issues, but it is just what I observed.

**Comment by tianon** [comment]
Given that the recommended usage for Rails itself is to add it to your project's `Gemfile` and use `bundle` to install it, [the `rails` official image](https://hub.docker.com/_/rails/) has been deprecated as of Jul 5 in favor of using [the `ruby` image](https://hub.docker.com/_/ruby/) directly (see https://github.com/docker-library/docs/pull/503 for more details).

Sorry for the inconvenience!  Since the image will not be receiving anything besides minor maintenance updates (version bumps for example), we're closing out old issues accordingly.  Thanks!
