### ISSUE TITLE
Failing on build

### ISSUE THREAD

**Issue by Deamoner** [docker-library/rails#41]
I used the exact Dockerfile that was in this repository, it would not run rails and errored out on that command. So I changed the base image from ruby to rails. Now everything builds and runs, but the app is still not available. Any help would be much appreciated.

**Comment by tianon** [comment]
Given that the recommended usage for Rails itself is to add it to your project's `Gemfile` and use `bundle` to install it, [the `rails` official image](https://hub.docker.com/_/rails/) has been deprecated as of Jul 5 in favor of using [the `ruby` image](https://hub.docker.com/_/ruby/) directly (see https://github.com/docker-library/docs/pull/503 for more details).

Sorry for the inconvenience!  Since the image will not be receiving anything besides minor maintenance updates (version bumps for example), we're closing out old issues accordingly.  Thanks!
